/**
 * Anchored Spec — OpenAPI Generator
 *
 * Generates OpenAPI 3.1 YAML stubs from `api-contract` EA entities.
 * Builds paths from `anchors.apis`, sets info from entity metadata,
 * and links back to the source entity.
 *
 * Design reference: docs/delivery-baseline.md (OpenAPI Generator)
 */

import type { BackstageEntity } from "../backstage/types.js";
import { getEntityAnchors, getEntityDescription, getEntityId, getEntityTitle, getSpecField } from "../backstage/accessors.js";
import { entityRefToFilenameSlug } from "../backstage/ref-utils.js";
import type {
  EaGenerator,
  EaGeneratorContext,
  GeneratedOutput,
  GenerationDrift,
} from "./index.js";

/** Shape of an api-contract entity's schema-specific fields. */
interface ApiContractFields {
  protocol?: string;
  specFormat?: string;
  specPath?: string;
  version?: string;
}

/**
 * OpenAPI Generator — generates OpenAPI 3.1 YAML stubs from api-contract entities.
 *
 * - Builds paths from `anchors.apis` (e.g., "POST /orders" → paths./orders.post)
 * - Sets info.title, info.description, info.version from entity fields
 * - Generates request/response stubs with TODO markers
 * - Links back via x-anchored-spec-entity extension
 * - Only generates for protocol=rest and specFormat=openapi (or unset)
 */
export const openapiGenerator: EaGenerator = {
  name: "openapi",
  schemas: ["api-contract"],
  outputFormat: "openapi",

  generate(entity: BackstageEntity, _ctx: EaGeneratorContext): GeneratedOutput[] {
    const fields: ApiContractFields = {
      protocol: getSpecField<string>(entity, "protocol"),
      specFormat: getSpecField<string>(entity, "specFormat"),
      specPath: getSpecField<string>(entity, "specPath"),
      version: getSpecField<string>(entity, "version"),
    };

    // Only generate for REST / OpenAPI contracts
    if (fields.protocol && fields.protocol !== "rest") return [];
    if (fields.specFormat && fields.specFormat !== "openapi") return [];

    const apis = getEntityAnchors(entity)?.apis ?? [];
    const version = fields.version ?? "0.1.0";

    // Build paths from API anchors
    const paths = buildPaths(apis);

    // Build the OpenAPI document as YAML
    const lines: string[] = [
      `# Generated by anchored-spec from ${getEntityId(entity)}`,
      `# Do not edit manually — regenerate with: anchored-spec generate`,
      `openapi: "3.1.0"`,
      `info:`,
      `  title: "${escapeYaml(getEntityTitle(entity))}"`,
      `  description: "${escapeYaml(getEntityDescription(entity))}"`,
      `  version: "${escapeYaml(version)}"`,
      `  x-anchored-spec-entity: "${getEntityId(entity)}"`,
    ];

    if (Object.keys(paths).length > 0) {
      lines.push(`paths:`);
      for (const [path, methods] of Object.entries(paths)) {
        lines.push(`  ${path}:`);
        for (const method of methods) {
          lines.push(`    ${method}:`);
          lines.push(`      summary: "TODO: describe ${method.toUpperCase()} ${path}"`);
          lines.push(`      operationId: "${generateOperationId(method, path)}"`);
          lines.push(`      responses:`);
          lines.push(`        "200":`);
          lines.push(`          description: "TODO: describe response"`);
        }
      }
    } else {
      lines.push(`paths: {}`);
    }

    lines.push(``);

    const slug = entityRefToFilenameSlug(getEntityId(entity));
    return [
      {
        relativePath: `${slug}.openapi.yaml`,
        content: lines.join("\n"),
        contentType: "yaml",
        sourceEntityRef: getEntityId(entity),
        description: `OpenAPI 3.1 stub for ${getEntityTitle(entity)}`,
        overwrite: true,
      },
    ];
  },

  diff(currentOutput: string, entity: BackstageEntity, ctx: EaGeneratorContext): GenerationDrift[] {
    const drifts: GenerationDrift[] = [];
    const generated = this.generate(entity, ctx);
    if (generated.length === 0) return [];

    const expectedContent = generated[0]!.content;
    const slug = entityRefToFilenameSlug(getEntityId(entity));

    if (normalizeWhitespace(currentOutput) !== normalizeWhitespace(expectedContent)) {
      drifts.push({
        filePath: `${slug}.openapi.yaml`,
        sourceEntityRef: getEntityId(entity),
        message: "OpenAPI spec has been manually modified and differs from what would be generated",
        suggestion: "review",
      });
    }

    return drifts;
  },
};

// ─── Helpers ────────────────────────────────────────────────────────────────────

/** Parse API anchor strings into path→methods mapping. */
function buildPaths(apis: string[]): Record<string, string[]> {
  const paths: Record<string, string[]> = {};

  for (const api of apis) {
    const parts = api.split(" ");
    if (parts.length < 2) continue;
    const method = parts[0]!.toLowerCase();
    const path = parts.slice(1).join(" ");

    if (!paths[path]) paths[path] = [];
    paths[path]!.push(method);
  }

  // Sort methods for deterministic output
  for (const path of Object.keys(paths)) {
    paths[path]!.sort();
  }

  return paths;
}

/** Generate an operationId from method + path. */
function generateOperationId(method: string, path: string): string {
  const cleanPath = path
    .replace(/\{([^}]+)\}/g, "By$1")
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  const parts = cleanPath.split("-").filter(Boolean);
  const camelCase = parts
    .map((p, i) => (i === 0 ? p.toLowerCase() : p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()))
    .join("");

  return `${method}${camelCase.charAt(0).toUpperCase()}${camelCase.slice(1)}`;
}

/** Escape special characters for YAML string values. */
function escapeYaml(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/** Normalize whitespace for comparison. */
function normalizeWhitespace(str: string): string {
  return str.replace(/\r\n/g, "\n").replace(/\s+$/gm, "").trim();
}
