/**
 * CI integration recipe generator
 *
 * Generates GitHub Actions workflow and pre-commit hook for
 * anchored-spec validation in CI pipelines.
 */

import { mkdirSync, writeFileSync, existsSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";

export interface CiRecipeResult {
  created: string[];
  skipped: string[];
  overwritten: string[];
}

export interface CiRecipeOptions {
  force?: boolean;
}

// ── GitHub Actions Workflow ─────────────────────────────────────────────────────

export function generateGitHubAction(): string {
  return `# Anchored Spec — Architecture Validation
# Validates EA entities, checks trace integrity, and detects drift on every PR.
# Generated by: npx anchored-spec init --ci

name: Architecture Validation

on:
  pull_request:
    branches: [main]
    paths:
      - 'catalog-info.yaml'
      - 'catalog/**'
      - 'docs/**'
      - '.anchored-spec/**'
  push:
    branches: [main]
    paths:
      - 'catalog-info.yaml'
      - 'catalog/**'
      - 'docs/**'
      - '.anchored-spec/**'

jobs:
  validate:
    name: EA Spec Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install anchored-spec
        run: npm install -g anchored-spec

      - name: Validate entities
        run: anchored-spec validate --strict

      - name: Check trace integrity
        run: anchored-spec trace --check

      - name: Detect drift
        run: anchored-spec drift --severity error

      - name: Semantic diff (PR only)
        if: github.event_name == 'pull_request'
        run: |
          anchored-spec diff --base origin/\${{ github.base_ref }} --json > /tmp/ea-diff.json
          anchored-spec diff --base origin/\${{ github.base_ref }} --compat
        continue-on-error: true

      - name: Summary
        if: always()
        run: anchored-spec status
`;
}

// ── Pre-commit Hook ─────────────────────────────────────────────────────────────

export function generatePreCommitHook(): string {
  return `#!/bin/sh
# Anchored Spec — Pre-commit hook
# Validates EA entities before allowing commits.
# Generated by: npx anchored-spec init --ci
#
# Install: cp .anchored-spec/hooks/pre-commit .git/hooks/pre-commit
# Or:      npx anchored-spec init --ci (auto-installs)

set -e

# Check if any EA entity files are staged
STAGED_ENTITIES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(catalog-info\\.yaml|catalog/.+\\.(yaml|yml))$' || true)
STAGED_DOCS=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^docs/.+\\.md$' || true)
STAGED_CONFIG=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^\\.anchored-spec/' || true)

if [ -z "$STAGED_ENTITIES" ] && [ -z "$STAGED_DOCS" ] && [ -z "$STAGED_CONFIG" ]; then
  exit 0
fi

echo "🏛  Anchored Spec — Pre-commit validation"

# Validate entities if the model or config changed
if [ -n "$STAGED_ENTITIES" ] || [ -n "$STAGED_CONFIG" ]; then
  echo "  → Validating catalog entities..."
  npx anchored-spec validate --strict 2>&1 | tail -3
fi

# Check trace integrity if docs changed
if [ -n "$STAGED_DOCS" ]; then
  echo "  → Checking trace integrity..."
  npx anchored-spec trace --check 2>&1 | tail -3
fi

echo "  ✓ Pre-commit checks passed"
`;
}

// ── Husky config (package.json-friendly) ────────────────────────────────────────

export function generateHuskyHook(): string {
  return `#!/bin/sh
# Anchored Spec — Husky pre-commit hook
# Add to .husky/pre-commit or run: npx anchored-spec init --ci
. "$(dirname "$0")/_/husky.sh"

npx anchored-spec validate --strict
npx anchored-spec trace --check
`;
}

// ── Writer ──────────────────────────────────────────────────────────────────────

export function writeCiRecipes(
  projectRoot: string,
  options?: CiRecipeOptions,
): CiRecipeResult {
  const created: string[] = [];
  const skipped: string[] = [];
  const overwritten: string[] = [];

  const filesToWrite: Array<{ rel: string; content: string; executable?: boolean }> = [
    {
      rel: join(".github", "workflows", "ea-validation.yml"),
      content: generateGitHubAction(),
    },
    {
      rel: join(".anchored-spec", "hooks", "pre-commit"),
      content: generatePreCommitHook(),
      executable: true,
    },
  ];

  for (const { rel, content, executable } of filesToWrite) {
    const abs = join(projectRoot, rel);
    if (existsSync(abs)) {
      if (options?.force) {
        writeFileSync(abs, content, "utf-8");
        if (executable) chmodSync(abs, 0o755);
        overwritten.push(rel);
      } else {
        skipped.push(rel);
      }
    } else {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content, "utf-8");
      if (executable) chmodSync(abs, 0o755);
      created.push(rel);
    }
  }

  return { created, skipped, overwritten };
}
