import { describe, it, expect } from "vitest";
import { validateSchema } from "../validate.js";

describe("change-verification schema", () => {
  it("accepts valid change verification data", () => {
    const data = {
      changeId: "CHG-2025-0001-add-login",
      commands: [
        { name: "verify", command: "anchored-spec verify --strict", required: true, status: "pending" },
        { name: "drift", command: "anchored-spec drift --fail-on-missing", required: true, status: "passed" },
      ],
      driftChecks: ["semantic"],
      evidence: { collected: false, collectedAt: null },
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(true);
  });

  it("accepts minimal valid data (changeId + commands)", () => {
    const data = {
      changeId: "CHG-2025-0002-fix-bug",
      commands: [],
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(true);
  });

  it("rejects missing required changeId", () => {
    const data = {
      commands: [
        { name: "verify", command: "anchored-spec verify", required: true },
      ],
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.message.includes("changeId"))).toBe(true);
  });

  it("rejects invalid changeId pattern", () => {
    const data = {
      changeId: "not-a-valid-id",
      commands: [],
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(false);
  });

  it("rejects unknown fields (additionalProperties: false)", () => {
    const data = {
      changeId: "CHG-2025-0001-test",
      commands: [],
      unknownField: true,
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.message.includes("additional"))).toBe(true);
  });

  it("rejects invalid command status enum", () => {
    const data = {
      changeId: "CHG-2025-0001-test",
      commands: [
        { name: "verify", command: "anchored-spec verify", required: true, status: "invalid" },
      ],
    };
    const result = validateSchema(data, "change-verification");
    expect(result.valid).toBe(false);
  });

  it("validates the sidecar stub format from create command", () => {
    // This matches the exact format generated by `create change`
    const stub = {
      $schema: "../../schemas/change-verification.schema.json",
      changeId: "CHG-2025-0001-add-feature",
      commands: [
        { name: "verify", command: "anchored-spec verify --strict", required: true, status: "pending" },
        { name: "drift", command: "anchored-spec drift --fail-on-missing", required: true, status: "pending" },
      ],
      driftChecks: ["semantic"],
      evidence: { collected: false, collectedAt: null },
    };
    const result = validateSchema(stub, "change-verification");
    expect(result.valid).toBe(true);
  });
});
