/**
 * Anchored Spec — Enterprise Architecture Types
 *
 * Core type definitions for the EA extension. All EA artifacts share a
 * common base shape (`EaArtifactBase`) and extend it with kind-specific fields.
 *
 * Design reference: docs/ea-unified-artifact-model.md
 */

// ─── Domains ────────────────────────────────────────────────────────────────────

/** The six EA domains, each grouping related artifact kinds. */
export type EaDomain =
  | "systems"
  | "delivery"
  | "data"
  | "information"
  | "business"
  | "transitions";

/** All registered EA domains. */
export const EA_DOMAINS: readonly EaDomain[] = [
  "systems",
  "delivery",
  "data",
  "information",
  "business",
  "transitions",
] as const;

// ─── Status & Confidence ────────────────────────────────────────────────────────

/**
 * Lifecycle status of an artifact.
 *
 * EA-native lifecycle: draft → active → deprecated → retired
 * Legacy-compat lifecycle: draft → planned → active → shipped → deprecated → retired
 */
export type ArtifactStatus =
  | "draft"
  | "planned"
  | "active"
  | "shipped"
  | "deprecated"
  | "retired"
  | "deferred";

/**
 * How this artifact's information was established.
 *
 * - `declared` — Human-authored, reviewed, intentional (highest trust)
 * - `observed` — Derived from an authoritative external source (medium trust)
 * - `inferred` — Generated by discovery heuristics, needs review (lowest trust)
 */
export type ArtifactConfidence = "declared" | "observed" | "inferred";

// ─── Anchors ────────────────────────────────────────────────────────────────────

/**
 * Anchor points binding an artifact to observable code, APIs, schemas,
 * infrastructure, and other verifiable locations. Resolvers use anchors
 * to detect drift between declared and observed state.
 *
 * Replaces and extends the existing `SemanticRefs` model.
 */
export interface EaAnchors {
  /** Code symbols: class names, function names, exported constants */
  symbols?: string[];

  /** API endpoints: "POST /orders", "GET /orders/:id" */
  apis?: string[];

  /** Event topics/types: "order.created", "payment.processed" */
  events?: string[];

  /** Schema references: "OrderSchema", "orders.order" */
  schemas?: string[];

  /** Infrastructure references: "terraform:module.order_service", "kubernetes:deployment/order-service" */
  infra?: string[];

  /** Catalog references: "service:order-service", "dataset:orders" */
  catalogRefs?: string[];

  /** IAM references: "aws:iam-role/order-service" */
  iam?: string[];

  /** Network references: "aws:security-group/sg-12345" */
  network?: string[];

  /** Status/state enum values: "open", "closed", "pending" */
  statuses?: string[];

  /** State machine transitions: "open→processing", "processing→completed" */
  transitions?: string[];

  /** Extensible anchors for tools not covered above */
  other?: Record<string, string[]>;
}

// ─── Relations ──────────────────────────────────────────────────────────────────

/**
 * A directional typed link between two artifacts.
 * Only canonical (forward) directions are stored; inverses are computed
 * by the graph builder.
 */
export interface EaRelation {
  /** Relation type (canonical direction only). */
  type: string;

  /** Target artifact ID. */
  target: string;

  /** Human-readable description of this specific relation instance. */
  description?: string;

  /** How critical this relation is. */
  criticality?: "low" | "medium" | "high" | "critical";

  /** Whether this relation is still active. */
  status?: "active" | "deprecated";
}

// ─── Trace Refs ─────────────────────────────────────────────────────────────────

/** A trace link to an external document, URL, or artifact. */
export interface EaTraceRef {
  /** Path to external document, URL, or artifact ID. */
  path: string;

  /** Role of this trace link. */
  role?:
    | "specification"
    | "evidence"
    | "rationale"
    | "context"
    | "implementation"
    | "test";

  /** Human-readable label. */
  label?: string;
}

// ─── Risk & Compliance ──────────────────────────────────────────────────────────

export interface EaRiskAssessment {
  level: "low" | "medium" | "high" | "critical";
  description?: string;
  mitigations?: string[];
}

export interface EaComplianceMetadata {
  /** Compliance frameworks: "SOC2", "HIPAA", "PCI-DSS" */
  frameworks?: string[];
  /** References to control artifact IDs */
  controls?: string[];
  /** ISO 8601 timestamp */
  lastAuditedAt?: string;
  /** ISO 8601 timestamp */
  nextAuditDue?: string;
}

// ─── Artifact Base Shape ────────────────────────────────────────────────────────

/**
 * The unified base shape shared by all EA artifacts.
 * Every kind extends this with additional kind-specific fields.
 *
 * Design reference: docs/ea-unified-artifact-model.md §Unified Base Shape
 *
 * @deprecated Use `BackstageEntity` from `./backstage/types.js` instead.
 * This type is retained for backward compatibility during migration.
 * Use the accessor functions from `./backstage/accessors.js` to read fields
 * from BackstageEntity in a way that parallels EaArtifactBase field access.
 */
export interface EaArtifactBase {
  /** Artifact identifier: `{domain}/{KIND_PREFIX}-{slug}` */
  id: string;

  /** Schema version of this artifact's content (team-managed). */
  schemaVersion: string;

  /** The kind discriminator — determines which extended fields apply. */
  kind: string;

  /** Human-readable title. */
  title: string;

  /** Lifecycle status. */
  status: ArtifactStatus;

  /** Human-readable summary of what this artifact represents. */
  summary: string;

  /** Team or individual owners. */
  owners: string[];

  /** How this artifact's information was established. */
  confidence: ArtifactConfidence;

  /** Freeform tags for filtering and grouping. */
  tags?: string[];

  /** Typed directional relations to other artifacts. */
  relations?: EaRelation[];

  /** Anchor points to observable code/infra/APIs. */
  anchors?: EaAnchors;

  /** Trace links to external documents, evidence, rationale. */
  traceRefs?: EaTraceRef[];

  /** Risk assessment metadata. */
  risk?: EaRiskAssessment;

  /** Compliance metadata. */
  compliance?: EaComplianceMetadata;

  /** Extensible metadata for plugins and custom tooling. */
  extensions?: Record<string, unknown>;
}

// ─── Kind-Specific Artifact Types (Phase A — Systems) ───────────────────────────

export interface ApplicationArtifact extends EaArtifactBase {
  kind: "application";
  technology?: {
    language?: string;
    framework?: string;
    runtime?: string;
  };
  repository?: string;
}

export interface ServiceArtifact extends EaArtifactBase {
  kind: "service";
  /** Service protocol if known. */
  protocol?: string;
}

export interface ApiContractArtifact extends EaArtifactBase {
  kind: "api-contract";
  protocol?: "rest" | "graphql" | "grpc" | "soap";
  specFormat?: "openapi" | "graphql-sdl" | "protobuf" | "asyncapi" | "custom";
  specPath?: string;
  version?: string;
}

export interface EventContractArtifact extends EaArtifactBase {
  kind: "event-contract";
  protocol?: "kafka" | "rabbitmq" | "sqs" | "sns" | "eventbridge" | "nats" | "custom";
  specFormat?: "asyncapi" | "avro" | "protobuf" | "json-schema" | "custom";
  specPath?: string;
  version?: string;
}

export interface IntegrationArtifact extends EaArtifactBase {
  kind: "integration";
  sourceSystem?: string;
  targetSystem?: string;
  pattern?: "sync-request" | "async-event" | "batch" | "streaming" | "file-transfer";
  protocol?: string;
}

export interface SystemInterfaceArtifact extends EaArtifactBase {
  kind: "system-interface";
  direction: "inbound" | "outbound" | "bidirectional";
  protocol?: "rest" | "graphql" | "grpc" | "soap" | "sftp" | "mq" | "custom";
  externalSystem?: string;
  ownership: "owned" | "external" | "shared";
  sla?: {
    availability?: string;
    latencyP99?: string;
    throughput?: string;
  };
}

export interface ConsumerArtifact extends EaArtifactBase {
  kind: "consumer";
  consumesContracts: string[];
  consumerType: "internal" | "external" | "partner";
  contact?: {
    team?: string;
    email?: string;
    slackChannel?: string;
  };
  quotas?: {
    rateLimit?: string;
    dailyLimit?: number;
    burstLimit?: number;
  };
  contractVersion?: string;
}

// ─── Kind-Specific Artifact Types (Phase A — Delivery) ──────────────────────────

export interface PlatformArtifact extends EaArtifactBase {
  kind: "platform";
  platformType?: "kubernetes" | "serverless" | "vm" | "bare-metal" | "paas" | "custom";
  provider?: string;
  region?: string;
}

export interface DeploymentArtifact extends EaArtifactBase {
  kind: "deployment";
  environment?: string;
  replicas?: number;
  resources?: Record<string, string>;
}

export interface RuntimeClusterArtifact extends EaArtifactBase {
  kind: "runtime-cluster";
  clusterType?: "kubernetes" | "ecs" | "nomad" | "swarm" | "custom";
  provider?: string;
  region?: string;
  nodeCount?: number;
}

export interface NetworkZoneArtifact extends EaArtifactBase {
  kind: "network-zone";
  zoneType?: "public" | "private" | "dmz" | "restricted";
  cidr?: string;
  provider?: string;
}

export interface IdentityBoundaryArtifact extends EaArtifactBase {
  kind: "identity-boundary";
  boundaryType?: "oauth2" | "saml" | "mtls" | "iam-role" | "service-account" | "custom";
  provider?: string;
  scope?: string;
}

export interface CloudResourceArtifact extends EaArtifactBase {
  kind: "cloud-resource";
  provider: "aws" | "gcp" | "azure" | "other";
  resourceType: string;
  region?: string;
  account?: string;
  resourceId?: string;
  costCenter?: string;
  provisionedBy?:
    | "terraform"
    | "cloudformation"
    | "pulumi"
    | "manual"
    | "cdk"
    | "other";
  technology?: {
    engine?: string;
    version?: string;
    tier?: string;
  };
}

export interface EnvironmentArtifact extends EaArtifactBase {
  kind: "environment";
  tier:
    | "production"
    | "staging"
    | "development"
    | "qa"
    | "sandbox"
    | "dr"
    | "other";
  isProduction: boolean;
  platforms?: string[];
  networkZones?: string[];
  accessLevel?: "restricted" | "team" | "org" | "public";
  maxDataClassification?: string;
  promotesFrom?: string;
  promotesTo?: string;
}

export interface TechnologyStandardArtifact extends EaArtifactBase {
  kind: "technology-standard";
  category:
    | "language"
    | "framework"
    | "database"
    | "messaging"
    | "runtime"
    | "cloud-service"
    | "tool"
    | "protocol"
    | "other";
  technology: string;
  approvedVersions?: string[];
  deprecatedVersions?: string[];
  scope?: {
    domains?: string[];
    environments?: string[];
    teams?: string[];
  };
  approvedAt?: string;
  reviewBy?: string;
  alternatives?: string[];
  rationale?: string;
}

// ─── Kind-Specific Artifact Types (Phase 2B — Data) ────────────────────────────

export interface LogicalDataModelArtifact extends EaArtifactBase {
  kind: "logical-data-model";
  attributes: Array<{
    name: string;
    type: string;
    required?: boolean;
    description?: string;
    classification?: string;
  }>;
  entityRelations?: Array<{
    target: string;
    cardinality: "1:1" | "1:N" | "N:1" | "N:M";
    description?: string;
  }>;
  boundedContext?: string;
  isAggregateRoot?: boolean;
}

export interface PhysicalSchemaArtifact extends EaArtifactBase {
  kind: "physical-schema";
  engine: string;
  schemaName?: string;
  tables?: Array<{
    name: string;
    columns: Array<{
      name: string;
      type: string;
      nullable?: boolean;
      primaryKey?: boolean;
      foreignKey?: { table: string; column: string };
      description?: string;
    }>;
    indexes?: Array<{
      name: string;
      columns: string[];
      unique?: boolean;
    }>;
  }>;
  managedBy?: "migrations" | "orm" | "manual" | "schema-registry" | "other";
  sourcePath?: string;
}

export interface DataStoreArtifact extends EaArtifactBase {
  kind: "data-store";
  technology: {
    engine: string;
    version?: string;
    category: "relational" | "document" | "key-value" | "graph" | "columnar" | "time-series" | "search" | "cache" | "message-store" | "object-store" | "data-lake" | "data-warehouse" | "other";
  };
  environment?: string;
  dataVolume?: {
    rowCount?: string;
    sizeOnDisk?: string;
    growthRate?: string;
  };
  backup?: {
    frequency?: string;
    retentionPeriod?: string;
    pointInTimeRecovery?: boolean;
  };
  isShared?: boolean;
}

export interface LineageArtifact extends EaArtifactBase {
  kind: "lineage";
  source: { artifactId: string; description?: string };
  destination: { artifactId: string; description?: string };
  mechanism: "etl" | "elt" | "streaming" | "cdc" | "api-pull" | "replication" | "manual" | "other";
  executedBy?: string;
  transformation?: string;
  schedule?: "real-time" | "hourly" | "daily" | "weekly" | "on-demand" | "custom";
  latency?: string;
  qualityChecks?: string[];
}

export interface MasterDataDomainArtifact extends EaArtifactBase {
  kind: "master-data-domain";
  entities: string[];
  steward: { team: string; contact?: string };
  goldenSource?: string;
  governanceRules?: string[];
  matchingStrategy?: string;
}

export interface DataQualityRuleArtifact extends EaArtifactBase {
  kind: "data-quality-rule";
  ruleType: "not-null" | "unique" | "referential-integrity" | "range" | "format" | "freshness" | "row-count" | "custom";
  appliesTo: string[];
  assertion: string;
  expression?: string;
  executor?: string;
  schedule?: string;
  onFailure: "block" | "alert" | "log";
  threshold?: { maxFailureRate?: number; maxFailureCount?: number };
}

export interface DataProductArtifact extends EaArtifactBase {
  kind: "data-product";
  domain: string;
  outputPorts: Array<{
    name: string;
    type: "api" | "table" | "file" | "stream" | "dataset";
    format?: string;
    location?: string;
    contractRef?: string;
  }>;
  inputPorts?: Array<{
    name: string;
    sourceRef: string;
    description?: string;
  }>;
  sla?: { freshness?: string; availability?: string; quality?: string };
  qualityRules?: string[];
  catalog?: { catalogRef?: string; tags?: string[]; description?: string };
}

// ─── Information Domain ─────────────────────────────────────────────────────────

export interface InformationConceptArtifact extends EaArtifactBase {
  kind: "information-concept";
  domain: string;
  glossaryTerms?: string[];
  decomposesInto?: string[];
  specializationOf?: string;
  synonyms?: string[];
}

export interface CanonicalEntityArtifact extends EaArtifactBase {
  kind: "canonical-entity";
  attributes: Array<{
    name: string;
    type: string;
    required?: boolean;
    description?: string;
    classification?: string;
    example?: string;
  }>;
  conceptRef?: string;
  entityVersion?: string;
  governanceStatus?: "proposed" | "ratified" | "under-review";
}

export interface InformationExchangeArtifact extends EaArtifactBase {
  kind: "information-exchange";
  source: { artifactId: string; role?: string };
  destination: { artifactId: string; role?: string };
  exchangedEntities: string[];
  purpose: string;
  trigger?: "event" | "request" | "scheduled" | "manual";
  implementingContracts?: string[];
  classificationLevel?: string;
  legalBasis?: string;
}

export interface ClassificationArtifact extends EaArtifactBase {
  kind: "classification";
  level: string;
  requiredControls: Array<{
    control: string;
    description: string;
    enforcedBy?: string;
  }>;
  regulations?: string[];
  handling?: {
    encryption?: "at-rest" | "in-transit" | "both" | "not-required";
    accessControl?: string;
    auditLogging?: boolean;
    masking?: string;
    crossBorderRestrictions?: string;
  };
  parentClassification?: string;
}

export interface RetentionPolicyArtifact extends EaArtifactBase {
  kind: "retention-policy";
  appliesTo: string[];
  retention: {
    duration: string;
    basis: string;
    startEvent?: string;
  };
  disposal: {
    method: "delete" | "anonymize" | "archive" | "aggregate";
    description?: string;
    automatedBy?: string;
  };
  legalBasis?: string;
  exceptions?: Array<{
    condition: string;
    extendedDuration?: string;
  }>;
  lastVerifiedAt?: string;
}

export interface GlossaryTermArtifact extends EaArtifactBase {
  kind: "glossary-term";
  definition: string;
  domain: string;
  synonyms?: string[];
  antonymsOrConfusables?: Array<{
    term: string;
    distinction: string;
  }>;
  relatedConcepts?: string[];
  examples?: string[];
  approvedBy?: string;
}

// ─── Business Domain ────────────────────────────────────────────────────────────

export interface MissionArtifact extends EaArtifactBase {
  kind: "mission";
  timeHorizon?: "short-term" | "medium-term" | "long-term" | "perpetual";
  keyResults?: Array<{
    id: string;
    description: string;
    metric?: string;
    target?: string;
    currentValue?: string;
  }>;
  strategicThemes?: string[];
  sponsor?: string;
}

export interface CapabilityArtifact extends EaArtifactBase {
  kind: "capability";
  level: number;
  parentCapability?: string;
  maturity?: "initial" | "developing" | "defined" | "managed" | "optimized";
  strategicImportance?: "commodity" | "differentiating" | "core";
  investmentProfile?: "invest" | "maintain" | "divest" | "evaluate";
  heatMap?: {
    businessValue?: "low" | "medium" | "high";
    technicalHealth?: "poor" | "fair" | "good" | "excellent";
    risk?: "low" | "medium" | "high" | "critical";
  };
}

export interface ValueStreamArtifact extends EaArtifactBase {
  kind: "value-stream";
  stages: Array<{
    id: string;
    name: string;
    description?: string;
    supportingCapabilities: string[];
    duration?: string;
    bottleneck?: boolean;
  }>;
  customer: string;
  valueProposition: string;
  trigger?: string;
  outcome?: string;
}

export interface ProcessArtifact extends EaArtifactBase {
  kind: "process";
  steps?: Array<{
    id: string;
    name: string;
    description?: string;
    actor?: string;
    systemRef?: string;
    automated?: boolean;
  }>;
  implementsCapabilities?: string[];
  trigger?: string;
  outcome?: string;
  frequency?: string;
  processOwner?: string;
  regulated?: boolean;
}

export interface OrgUnitArtifact extends EaArtifactBase {
  kind: "org-unit";
  unitType: "team" | "department" | "division" | "business-unit" | "guild" | "chapter" | "other";
  parentUnit?: string;
  lead?: string;
  size?: number;
  locations?: string[];
  costCenter?: string;
}

export interface PolicyObjectiveArtifact extends EaArtifactBase {
  kind: "policy-objective";
  category: "sla" | "compliance" | "security" | "operational" | "financial" | "data-governance" | "other";
  objective: string;
  target?: {
    metric: string;
    threshold: string;
    currentValue?: string;
  };
  enforcedBy?: string[];
  regulatoryRef?: string;
  reviewCadence?: string;
}

export interface BusinessServiceArtifact extends EaArtifactBase {
  kind: "business-service";
  serviceType: "customer-facing" | "internal" | "partner" | "shared";
  channels?: string[];
  revenueImpact?: "direct" | "indirect" | "cost-center";
  serviceLevel?: string;
  implementedByCapabilities?: string[];
}

export interface ControlArtifact extends EaArtifactBase {
  kind: "control";
  controlType: "preventive" | "detective" | "corrective" | "directive";
  implementation: "automated" | "manual" | "hybrid";
  assertion: string;
  mechanism?: string;
  frequency?: "continuous" | "hourly" | "daily" | "weekly" | "monthly" | "on-demand" | "event-triggered";
  producesEvidence?: string;
  onViolation?: {
    action: "block" | "alert" | "escalate" | "log" | "auto-remediate";
    target?: string;
    description?: string;
  };
  lastExecutedAt?: string;
  frameworks?: string[];
}

// ─── Transitions Domain ─────────────────────────────────────────────────────────

export interface BaselineArtifact extends EaArtifactBase {
  kind: "baseline";
  scope: {
    domains?: EaDomain[];
    kinds?: string[];
    tags?: string[];
    description: string;
  };
  capturedAt: string;
  artifactRefs: string[];
  assumptions?: string[];
  exceptions?: string[];
  baselineVersion?: string;
}

export interface TargetArtifact extends EaArtifactBase {
  kind: "target";
  scope: {
    domains?: EaDomain[];
    kinds?: string[];
    tags?: string[];
    description: string;
  };
  effectiveBy: string;
  artifactRefs: string[];
  principles?: string[];
  successMetrics?: Array<{
    id: string;
    metric: string;
    target: string;
    currentValue?: string;
  }>;
}

export interface TransitionMilestone {
  id: string;
  title: string;
  deliverables: string[];
  generates?: string[];
  criteria?: string[];
  status?: "pending" | "in-progress" | "complete" | "blocked";
  blockedReason?: string;
}

export interface TransitionRisk {
  id: string;
  description: string;
  likelihood: "low" | "medium" | "high";
  impact: "low" | "medium" | "high" | "critical";
  mitigation: string;
  owner?: string;
  status?: "open" | "mitigated" | "accepted" | "closed";
}

export interface TransitionPlanArtifact extends EaArtifactBase {
  kind: "transition-plan";
  baseline: string;
  target: string;
  milestones: TransitionMilestone[];
  milestoneDependencies?: Array<{
    milestone: string;
    dependsOn: string;
  }>;
  riskRegister?: TransitionRisk[];
  approvalPolicy?: {
    requiredApprovers: string[];
    approvedAt?: string;
    approvedBy?: string[];
  };
}

export interface MigrationWaveArtifact extends EaArtifactBase {
  kind: "migration-wave";
  transitionPlan: string;
  milestones: string[];
  sequenceOrder: number;
  scope: {
    create?: string[];
    modify?: string[];
    retire?: string[];
  };
  preconditions?: string[];
  rollbackStrategy?: string;
}

export interface ExceptionArtifact extends EaArtifactBase {
  kind: "exception";
  scope: {
    artifactIds?: string[];
    rules?: string[];
    domains?: EaDomain[];
  };
  approvedBy: string;
  approvedAt: string;
  expiresAt: string;
  reason: string;
  reviewSchedule?: "weekly" | "monthly" | "quarterly";
}

// ─── Legacy Subsumption Kinds ───────────────────────────────────────────────────

/** EARS behavior statement (shared with core types). */
export interface EaBehaviorStatement {
  id: string;
  text: string;
  format: "EARS";
  trigger?: string;
  precondition?: string;
  response: string;
}

/** A behavioral software requirement. */
export interface RequirementArtifact extends EaArtifactBase {
  kind: "requirement";
  behaviorStatements?: EaBehaviorStatement[];
  verification?: {
    coverageStatus: "none" | "partial" | "covered";
    testRefs?: string[];
  };
  category?: "functional" | "non-functional" | "policy";
  priority?: "must" | "should" | "could" | "wont";
  supersededBy?: string;
  statusReason?: string;
}

/** A security requirement aligned to NIST SP 800-53 or equivalent frameworks. */
export interface SecurityRequirementArtifact extends EaArtifactBase {
  kind: "security-requirement";
  controlFamily?: string;
  nistControl?: string;
  securityBaseline?: "low" | "moderate" | "high";
  implementationStatus?: "planned" | "partial" | "implemented" | "not-applicable";
  assessmentMethod?: "examine" | "interview" | "test";
  complianceFrameworks?: string[];
  priority?: "must" | "should" | "could" | "wont";
  supersededBy?: string;
  statusReason?: string;
}

/** A data requirement defining security classification and governance constraints. */
export interface DataRequirementArtifact extends EaArtifactBase {
  kind: "data-requirement";
  dataClassification?: "public" | "internal" | "confidential" | "restricted";
  fipsCategory?: "low" | "moderate" | "high";
  securityObjective?: "confidentiality" | "integrity" | "availability";
  dataTypes?: string[];
  complianceFrameworks?: string[];
  priority?: "must" | "should" | "could" | "wont";
  supersededBy?: string;
  statusReason?: string;
}

/** A technical requirement for infrastructure, network, and delivery systems. */
export interface TechnicalRequirementArtifact extends EaArtifactBase {
  kind: "technical-requirement";
  technologyLayer?: "network" | "compute" | "storage" | "identity" | "monitoring";
  implementationPattern?: string;
  protocols?: string[];
  performanceCriteria?: {
    metric: string;
    target: string;
    unit?: string;
  }[];
  priority?: "must" | "should" | "could" | "wont";
  supersededBy?: string;
  statusReason?: string;
}

/** An information requirement for content types and information flow governance. */
export interface InformationRequirementArtifact extends EaArtifactBase {
  kind: "information-requirement";
  informationType?: string;
  flowDirection?: "inbound" | "outbound" | "bidirectional";
  sensitivityLevel?: "public" | "internal" | "sensitive" | "restricted";
  requiredControls?: string[];
  complianceFrameworks?: string[];
  priority?: "must" | "should" | "could" | "wont";
  supersededBy?: string;
  statusReason?: string;
}

/** An implementation change record — auditable evidence of system modifications. */
export interface ChangeArtifact extends EaArtifactBase {
  kind: "change";
  changeType?: string;
  phase?: string;
  changeStatus?: string;
  scope?: { include?: string[]; exclude?: string[] };
  requirements?: string[];
  workflowVariant?: string;
  bugfixSpec?: {
    currentBehavior: string;
    expectedBehavior: string;
    rootCauseHypothesis?: string;
    regressionRisk?: string;
  };
  // NIST Configuration Management (SP 800-53 CM, SP 800-171)
  baselineRef?: string;
  configurationItem?: string;
  authorizedBy?: string;
  changeAdvisoryBoard?: boolean;
  authorizationStatus?: "pending" | "approved" | "rejected" | "emergency";
  // NIST RMF & CSF alignment
  nistFunction?: "identify" | "protect" | "detect" | "respond" | "recover" | "govern";
  riskImpact?: "none" | "low" | "moderate" | "high" | "critical";
  securityRelevant?: boolean;
  continuousMonitoring?: boolean;
  auditTrail?: Array<{
    timestamp: string;
    actor: string;
    action: string;
    detail?: string;
  }>;
}

/** An architecture decision record documenting a key design choice. */
export interface DecisionArtifact extends EaArtifactBase {
  kind: "decision";
  decision?: string;
  context?: string;
  rationale?: string;
  alternatives?: Array<{
    name: string;
    verdict: "chosen" | "rejected" | "deferred";
    reason?: string;
  }>;
  relatedRequirements?: string[];
  adDomain?: string;
  implications?: string;
  // NIST alignment
  nistFunction?: "identify" | "protect" | "detect" | "respond" | "recover" | "govern";
  riskFrameworkStep?: "prepare" | "categorize" | "select" | "implement" | "assess" | "authorize" | "monitor";
  zeroTrustComponent?: "policy-engine" | "policy-administrator" | "policy-enforcement-point" | "data-plane" | "control-plane";
  complianceFrameworks?: string[];
  riskLevel?: "low" | "moderate" | "high" | "critical";
  governanceImpact?: string;
}

// ─── Union Type ─────────────────────────────────────────────────────────────────

/**
 * Discriminated union of all artifact types.
 * @deprecated Use `BackstageEntity` instead. Individual kind types are
 * now represented via `BackstageEntity.spec` typed interfaces.
 */
export type EaArtifact =
  | ApplicationArtifact
  | ServiceArtifact
  | ApiContractArtifact
  | EventContractArtifact
  | IntegrationArtifact
  | SystemInterfaceArtifact
  | ConsumerArtifact
  | PlatformArtifact
  | DeploymentArtifact
  | RuntimeClusterArtifact
  | NetworkZoneArtifact
  | IdentityBoundaryArtifact
  | CloudResourceArtifact
  | EnvironmentArtifact
  | TechnologyStandardArtifact
  | LogicalDataModelArtifact
  | PhysicalSchemaArtifact
  | DataStoreArtifact
  | LineageArtifact
  | MasterDataDomainArtifact
  | DataQualityRuleArtifact
  | DataProductArtifact
  | InformationConceptArtifact
  | CanonicalEntityArtifact
  | InformationExchangeArtifact
  | ClassificationArtifact
  | RetentionPolicyArtifact
  | GlossaryTermArtifact
  | MissionArtifact
  | CapabilityArtifact
  | ValueStreamArtifact
  | ProcessArtifact
  | OrgUnitArtifact
  | PolicyObjectiveArtifact
  | BusinessServiceArtifact
  | ControlArtifact
  | BaselineArtifact
  | TargetArtifact
  | TransitionPlanArtifact
  | MigrationWaveArtifact
  | ExceptionArtifact
  | RequirementArtifact
  | SecurityRequirementArtifact
  | DataRequirementArtifact
  | TechnicalRequirementArtifact
  | InformationRequirementArtifact
  | ChangeArtifact
  | DecisionArtifact;

// ─── Kind Taxonomy ──────────────────────────────────────────────────────────────

/**
 * Metadata for a registered EA kind.
 * @deprecated Use `KindMappingEntry` from `./backstage/kind-mapping.js` instead.
 */
export interface EaKindEntry {
  kind: string;
  prefix: string;
  domain: EaDomain;
  description: string;
}

/**
 * All registered kinds and their metadata.
 * @deprecated Use `BACKSTAGE_KIND_REGISTRY` from `./backstage/kind-mapping.js` instead.
 */
export const EA_KIND_REGISTRY: readonly EaKindEntry[] = [
  // Systems domain
  { kind: "application", prefix: "APP", domain: "systems", description: "A deployable software system" },
  { kind: "service", prefix: "SVC", domain: "systems", description: "A runtime service component within an application" },
  { kind: "api-contract", prefix: "API", domain: "systems", description: "An API specification (REST, GraphQL, gRPC)" },
  { kind: "event-contract", prefix: "EVT", domain: "systems", description: "An async event/message contract" },
  { kind: "integration", prefix: "INT", domain: "systems", description: "A declared integration between two systems" },
  { kind: "system-interface", prefix: "SIF", domain: "systems", description: "An external system boundary interface" },
  { kind: "consumer", prefix: "CON", domain: "systems", description: "A declared consumer of an API or event" },
  // Delivery domain
  { kind: "platform", prefix: "PLAT", domain: "delivery", description: "A runtime platform (K8s cluster, serverless, etc.)" },
  { kind: "deployment", prefix: "DEPLOY", domain: "delivery", description: "A deployed instance of an application" },
  { kind: "runtime-cluster", prefix: "CLUSTER", domain: "delivery", description: "A compute cluster" },
  { kind: "network-zone", prefix: "ZONE", domain: "delivery", description: "A network security zone or boundary" },
  { kind: "identity-boundary", prefix: "IDB", domain: "delivery", description: "An identity/auth boundary" },
  { kind: "cloud-resource", prefix: "CLOUD", domain: "delivery", description: "A specific cloud resource (RDS instance, S3 bucket, etc.)" },
  { kind: "environment", prefix: "ENV", domain: "delivery", description: "A deployment environment (prod, staging, dev)" },
  { kind: "technology-standard", prefix: "TECH", domain: "delivery", description: "An approved technology standard" },
  // Data domain
  { kind: "logical-data-model", prefix: "LDM", domain: "data", description: "A logical data model describing entity attributes and relationships" },
  { kind: "physical-schema", prefix: "SCHEMA", domain: "data", description: "A physical database schema definition" },
  { kind: "data-store", prefix: "STORE", domain: "data", description: "A data storage system (database, cache, object store, etc.)" },
  { kind: "lineage", prefix: "LINEAGE", domain: "data", description: "A data lineage path from source to destination" },
  { kind: "master-data-domain", prefix: "MDM", domain: "data", description: "A master data domain with golden-source governance" },
  { kind: "data-quality-rule", prefix: "DQR", domain: "data", description: "A data quality rule defining assertions and enforcement" },
  { kind: "data-product", prefix: "DPROD", domain: "data", description: "A data product with defined ports, SLAs, and catalog metadata" },
  // Information domain
  { kind: "information-concept", prefix: "IC", domain: "information", description: "A high-level information concept within a business domain" },
  { kind: "canonical-entity", prefix: "CE", domain: "information", description: "A canonical data entity definition with typed attributes" },
  { kind: "information-exchange", prefix: "EXCH", domain: "information", description: "A declared information exchange between systems or domains" },
  { kind: "classification", prefix: "CLASS", domain: "information", description: "A data classification level with required controls" },
  { kind: "retention-policy", prefix: "RET", domain: "information", description: "A data retention policy with duration and disposal rules" },
  { kind: "glossary-term", prefix: "TERM", domain: "information", description: "A canonical glossary term with definition and domain" },
  // Business domain
  { kind: "mission", prefix: "MISSION", domain: "business", description: "A strategic mission or objective with key results" },
  { kind: "capability", prefix: "CAP", domain: "business", description: "A business capability with maturity and heat map" },
  { kind: "value-stream", prefix: "VS", domain: "business", description: "A value stream with stages and customer value" },
  { kind: "process", prefix: "PROC", domain: "business", description: "A business process with steps and automation" },
  { kind: "org-unit", prefix: "ORG", domain: "business", description: "An organizational unit (team, department, etc.)" },
  { kind: "policy-objective", prefix: "POL", domain: "business", description: "A policy objective with target metrics and enforcement" },
  { kind: "business-service", prefix: "BSVC", domain: "business", description: "A business service delivered to customers or partners" },
  { kind: "control", prefix: "CTRL", domain: "business", description: "A governance control with assertion and enforcement" },
  // Transitions domain
  { kind: "baseline", prefix: "BASELINE", domain: "transitions", description: "A point-in-time architecture snapshot" },
  { kind: "target", prefix: "TARGET", domain: "transitions", description: "A desired future architecture state" },
  { kind: "transition-plan", prefix: "PLAN", domain: "transitions", description: "A plan to move from baseline to target" },
  { kind: "migration-wave", prefix: "WAVE", domain: "transitions", description: "A batch of related changes within a transition" },
  { kind: "exception", prefix: "EXCEPT", domain: "transitions", description: "An approved exception to architecture policy" },
  // Requirements (cross-layer per NIST EA model)
  { kind: "requirement", prefix: "REQ", domain: "business", description: "A behavioral software requirement" },
  { kind: "security-requirement", prefix: "SREQ", domain: "systems", description: "A security requirement aligned to NIST SP 800-53 or equivalent frameworks" },
  { kind: "data-requirement", prefix: "DREQ", domain: "data", description: "A data requirement defining security classification and governance constraints" },
  { kind: "technical-requirement", prefix: "TREQ", domain: "delivery", description: "A technical requirement for infrastructure, network, and delivery systems" },
  { kind: "information-requirement", prefix: "IREQ", domain: "information", description: "An information requirement for content types and information flow governance" },
  // Decisions & changes
  { kind: "change", prefix: "CHG", domain: "transitions", description: "An implementation change record tracking work toward a target state" },
  { kind: "decision", prefix: "ADR", domain: "transitions", description: "An architecture decision record documenting a key design choice" },
] as const;

/**
 * Lookup helpers.
 * @deprecated Use kind-mapping functions from `./backstage/kind-mapping.js` instead.
 */
export function getKindEntry(kind: string): EaKindEntry | undefined {
  return EA_KIND_REGISTRY.find((e) => e.kind === kind);
}

/** @deprecated Use BACKSTAGE_KIND_REGISTRY instead. */
export function getKindsByDomain(domain: EaDomain): EaKindEntry[] {
  return EA_KIND_REGISTRY.filter((e) => e.domain === domain);
}

/** @deprecated Use mapLegacyKind() from backstage/kind-mapping.js instead. */
export function getKindPrefix(kind: string): string | undefined {
  return getKindEntry(kind)?.prefix;
}

/** @deprecated Use getEntityDomain() from backstage/accessors.js instead. */
export function getDomainForKind(kind: string): EaDomain | undefined {
  return getKindEntry(kind)?.domain;
}

// ─── ID Validation ──────────────────────────────────────────────────────────────

/**
 * Validates an EA artifact ID against the format: `{domain}/{PREFIX}-{slug}`
 * or the short form `{PREFIX}-{slug}`.
 *
 * @deprecated Legacy ID format. Backstage entities use entity references instead.
 */
export function isValidEaId(id: string, kind?: string): boolean {
  // Allow domain-qualified or short IDs
  const parts = id.includes("/") ? id.split("/") : [undefined, id];
  if (parts.length > 2) return false;

  const [domain, localId] = parts;

  // If domain provided, validate it
  if (domain && !EA_DOMAINS.includes(domain as EaDomain)) return false;

  // LocalId must be PREFIX-slug
  if (!localId || !localId.includes("-")) return false;

  // Extract prefix (everything before the first dash in slug portion)
  const dashIndex = localId.indexOf("-");
  const prefix = localId.substring(0, dashIndex);
  const slug = localId.substring(dashIndex + 1);

  if (!prefix || !slug) return false;

  // Slug must be kebab-case
  if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(slug)) return false;

  // If kind is provided, validate prefix matches
  if (kind) {
    const expected = getKindPrefix(kind);
    if (expected && expected !== prefix) return false;
  }

  return true;
}
