/**
 * Anchored Spec — Enterprise Architecture Types
 *
 * Core type definitions for the EA extension. All EA artifacts share a
 * common base shape (`EaArtifactBase`) and extend it with kind-specific fields.
 *
 * Design reference: docs/ea-unified-artifact-model.md
 */

// ─── Domains ────────────────────────────────────────────────────────────────────

/** The six EA domains, each grouping related artifact kinds. */
export type EaDomain =
  | "systems"
  | "delivery"
  | "data"
  | "information"
  | "business"
  | "transitions";

/** All registered EA domains. */
export const EA_DOMAINS: readonly EaDomain[] = [
  "systems",
  "delivery",
  "data",
  "information",
  "business",
  "transitions",
] as const;

// ─── Status & Confidence ────────────────────────────────────────────────────────

/**
 * Lifecycle status of an artifact.
 *
 * EA-native lifecycle: draft → active → deprecated → retired
 * Legacy-compat lifecycle: draft → planned → active → shipped → deprecated → retired
 */
export type ArtifactStatus =
  | "draft"
  | "planned"
  | "active"
  | "shipped"
  | "deprecated"
  | "retired"
  | "deferred";

/**
 * How this artifact's information was established.
 *
 * - `declared` — Human-authored, reviewed, intentional (highest trust)
 * - `observed` — Derived from an authoritative external source (medium trust)
 * - `inferred` — Generated by discovery heuristics, needs review (lowest trust)
 */
export type ArtifactConfidence = "declared" | "observed" | "inferred";

// ─── Anchors ────────────────────────────────────────────────────────────────────

/**
 * Anchor points binding an artifact to observable code, APIs, schemas,
 * infrastructure, and other verifiable locations. Resolvers use anchors
 * to detect drift between declared and observed state.
 *
 * Replaces and extends the existing `SemanticRefs` model.
 */
export interface EaAnchors {
  /** Code symbols: class names, function names, exported constants */
  symbols?: string[];

  /** API endpoints: "POST /orders", "GET /orders/:id" */
  apis?: string[];

  /** Event topics/types: "order.created", "payment.processed" */
  events?: string[];

  /** Schema references: "OrderSchema", "orders.order" */
  schemas?: string[];

  /** Infrastructure references: "terraform:module.order_service", "kubernetes:deployment/order-service" */
  infra?: string[];

  /** Catalog references: "service:order-service", "dataset:orders" */
  catalogRefs?: string[];

  /** IAM references: "aws:iam-role/order-service" */
  iam?: string[];

  /** Network references: "aws:security-group/sg-12345" */
  network?: string[];

  /** Extensible anchors for tools not covered above */
  other?: Record<string, string[]>;
}

// ─── Relations ──────────────────────────────────────────────────────────────────

/**
 * A directional typed link between two artifacts.
 * Only canonical (forward) directions are stored; inverses are computed
 * by the graph builder.
 */
export interface EaRelation {
  /** Relation type (canonical direction only). */
  type: string;

  /** Target artifact ID. */
  target: string;

  /** Human-readable description of this specific relation instance. */
  description?: string;

  /** How critical this relation is. */
  criticality?: "low" | "medium" | "high" | "critical";

  /** Whether this relation is still active. */
  status?: "active" | "deprecated";
}

// ─── Trace Refs ─────────────────────────────────────────────────────────────────

/** A trace link to an external document, URL, or artifact. */
export interface EaTraceRef {
  /** Path to external document, URL, or artifact ID. */
  path: string;

  /** Role of this trace link. */
  role?:
    | "specification"
    | "evidence"
    | "rationale"
    | "context"
    | "implementation"
    | "test";

  /** Human-readable label. */
  label?: string;
}

// ─── Risk & Compliance ──────────────────────────────────────────────────────────

export interface EaRiskAssessment {
  level: "low" | "medium" | "high" | "critical";
  description?: string;
  mitigations?: string[];
}

export interface EaComplianceMetadata {
  /** Compliance frameworks: "SOC2", "HIPAA", "PCI-DSS" */
  frameworks?: string[];
  /** References to control artifact IDs */
  controls?: string[];
  /** ISO 8601 timestamp */
  lastAuditedAt?: string;
  /** ISO 8601 timestamp */
  nextAuditDue?: string;
}

// ─── Artifact Base Shape ────────────────────────────────────────────────────────

/**
 * The unified base shape shared by all EA artifacts.
 * Every kind extends this with additional kind-specific fields.
 *
 * Design reference: docs/ea-unified-artifact-model.md §Unified Base Shape
 */
export interface EaArtifactBase {
  /** Artifact identifier: `{domain}/{KIND_PREFIX}-{slug}` */
  id: string;

  /** Schema version of this artifact's content (team-managed). */
  schemaVersion: string;

  /** The kind discriminator — determines which extended fields apply. */
  kind: string;

  /** Human-readable title. */
  title: string;

  /** Lifecycle status. */
  status: ArtifactStatus;

  /** Human-readable summary of what this artifact represents. */
  summary: string;

  /** Team or individual owners. */
  owners: string[];

  /** How this artifact's information was established. */
  confidence: ArtifactConfidence;

  /** Freeform tags for filtering and grouping. */
  tags?: string[];

  /** Typed directional relations to other artifacts. */
  relations?: EaRelation[];

  /** Anchor points to observable code/infra/APIs. */
  anchors?: EaAnchors;

  /** Trace links to external documents, evidence, rationale. */
  traceRefs?: EaTraceRef[];

  /** Risk assessment metadata. */
  risk?: EaRiskAssessment;

  /** Compliance metadata. */
  compliance?: EaComplianceMetadata;

  /** Extensible metadata for plugins and custom tooling. */
  extensions?: Record<string, unknown>;
}

// ─── Kind-Specific Artifact Types (Phase A — Systems) ───────────────────────────

export interface ApplicationArtifact extends EaArtifactBase {
  kind: "application";
  technology?: {
    language?: string;
    framework?: string;
    runtime?: string;
  };
  repository?: string;
}

export interface ServiceArtifact extends EaArtifactBase {
  kind: "service";
  /** Service protocol if known. */
  protocol?: string;
}

export interface ApiContractArtifact extends EaArtifactBase {
  kind: "api-contract";
  protocol?: "rest" | "graphql" | "grpc" | "soap";
  specFormat?: "openapi" | "graphql-sdl" | "protobuf" | "asyncapi" | "custom";
  specPath?: string;
  version?: string;
}

export interface EventContractArtifact extends EaArtifactBase {
  kind: "event-contract";
  protocol?: "kafka" | "rabbitmq" | "sqs" | "sns" | "eventbridge" | "nats" | "custom";
  specFormat?: "asyncapi" | "avro" | "protobuf" | "json-schema" | "custom";
  specPath?: string;
  version?: string;
}

export interface IntegrationArtifact extends EaArtifactBase {
  kind: "integration";
  sourceSystem?: string;
  targetSystem?: string;
  pattern?: "sync-request" | "async-event" | "batch" | "streaming" | "file-transfer";
  protocol?: string;
}

export interface SystemInterfaceArtifact extends EaArtifactBase {
  kind: "system-interface";
  direction: "inbound" | "outbound" | "bidirectional";
  protocol?: "rest" | "graphql" | "grpc" | "soap" | "sftp" | "mq" | "custom";
  externalSystem?: string;
  ownership: "owned" | "external" | "shared";
  sla?: {
    availability?: string;
    latencyP99?: string;
    throughput?: string;
  };
}

export interface ConsumerArtifact extends EaArtifactBase {
  kind: "consumer";
  consumesContracts: string[];
  consumerType: "internal" | "external" | "partner";
  contact?: {
    team?: string;
    email?: string;
    slackChannel?: string;
  };
  quotas?: {
    rateLimit?: string;
    dailyLimit?: number;
    burstLimit?: number;
  };
  contractVersion?: string;
}

// ─── Kind-Specific Artifact Types (Phase A — Delivery) ──────────────────────────

export interface PlatformArtifact extends EaArtifactBase {
  kind: "platform";
  platformType?: "kubernetes" | "serverless" | "vm" | "bare-metal" | "paas" | "custom";
  provider?: string;
  region?: string;
}

export interface DeploymentArtifact extends EaArtifactBase {
  kind: "deployment";
  environment?: string;
  replicas?: number;
  resources?: Record<string, string>;
}

export interface RuntimeClusterArtifact extends EaArtifactBase {
  kind: "runtime-cluster";
  clusterType?: "kubernetes" | "ecs" | "nomad" | "swarm" | "custom";
  provider?: string;
  region?: string;
  nodeCount?: number;
}

export interface NetworkZoneArtifact extends EaArtifactBase {
  kind: "network-zone";
  zoneType?: "public" | "private" | "dmz" | "restricted";
  cidr?: string;
  provider?: string;
}

export interface IdentityBoundaryArtifact extends EaArtifactBase {
  kind: "identity-boundary";
  boundaryType?: "oauth2" | "saml" | "mtls" | "iam-role" | "service-account" | "custom";
  provider?: string;
  scope?: string;
}

export interface CloudResourceArtifact extends EaArtifactBase {
  kind: "cloud-resource";
  provider: "aws" | "gcp" | "azure" | "other";
  resourceType: string;
  region?: string;
  account?: string;
  resourceId?: string;
  costCenter?: string;
  provisionedBy?:
    | "terraform"
    | "cloudformation"
    | "pulumi"
    | "manual"
    | "cdk"
    | "other";
  technology?: {
    engine?: string;
    version?: string;
    tier?: string;
  };
}

export interface EnvironmentArtifact extends EaArtifactBase {
  kind: "environment";
  tier:
    | "production"
    | "staging"
    | "development"
    | "qa"
    | "sandbox"
    | "dr"
    | "other";
  isProduction: boolean;
  platforms?: string[];
  networkZones?: string[];
  accessLevel?: "restricted" | "team" | "org" | "public";
  maxDataClassification?: string;
  promotesFrom?: string;
  promotesTo?: string;
}

export interface TechnologyStandardArtifact extends EaArtifactBase {
  kind: "technology-standard";
  category:
    | "language"
    | "framework"
    | "database"
    | "messaging"
    | "runtime"
    | "cloud-service"
    | "tool"
    | "protocol"
    | "other";
  technology: string;
  approvedVersions?: string[];
  deprecatedVersions?: string[];
  scope?: {
    domains?: string[];
    environments?: string[];
    teams?: string[];
  };
  approvedAt?: string;
  reviewBy?: string;
  alternatives?: string[];
  rationale?: string;
}

// ─── Union Type ─────────────────────────────────────────────────────────────────

/** Discriminated union of all Phase A (systems + delivery) artifact types. */
export type EaArtifact =
  | ApplicationArtifact
  | ServiceArtifact
  | ApiContractArtifact
  | EventContractArtifact
  | IntegrationArtifact
  | SystemInterfaceArtifact
  | ConsumerArtifact
  | PlatformArtifact
  | DeploymentArtifact
  | RuntimeClusterArtifact
  | NetworkZoneArtifact
  | IdentityBoundaryArtifact
  | CloudResourceArtifact
  | EnvironmentArtifact
  | TechnologyStandardArtifact;

// ─── Kind Taxonomy ──────────────────────────────────────────────────────────────

/** Metadata for a registered EA kind. */
export interface EaKindEntry {
  kind: string;
  prefix: string;
  domain: EaDomain;
  description: string;
}

/** All Phase A (systems + delivery) kinds and their metadata. */
export const EA_KIND_REGISTRY: readonly EaKindEntry[] = [
  // Systems domain
  { kind: "application", prefix: "APP", domain: "systems", description: "A deployable software system" },
  { kind: "service", prefix: "SVC", domain: "systems", description: "A runtime service component within an application" },
  { kind: "api-contract", prefix: "API", domain: "systems", description: "An API specification (REST, GraphQL, gRPC)" },
  { kind: "event-contract", prefix: "EVT", domain: "systems", description: "An async event/message contract" },
  { kind: "integration", prefix: "INT", domain: "systems", description: "A declared integration between two systems" },
  { kind: "system-interface", prefix: "SIF", domain: "systems", description: "An external system boundary interface" },
  { kind: "consumer", prefix: "CON", domain: "systems", description: "A declared consumer of an API or event" },
  // Delivery domain
  { kind: "platform", prefix: "PLAT", domain: "delivery", description: "A runtime platform (K8s cluster, serverless, etc.)" },
  { kind: "deployment", prefix: "DEPLOY", domain: "delivery", description: "A deployed instance of an application" },
  { kind: "runtime-cluster", prefix: "CLUSTER", domain: "delivery", description: "A compute cluster" },
  { kind: "network-zone", prefix: "ZONE", domain: "delivery", description: "A network security zone or boundary" },
  { kind: "identity-boundary", prefix: "IDB", domain: "delivery", description: "An identity/auth boundary" },
  { kind: "cloud-resource", prefix: "CLOUD", domain: "delivery", description: "A specific cloud resource (RDS instance, S3 bucket, etc.)" },
  { kind: "environment", prefix: "ENV", domain: "delivery", description: "A deployment environment (prod, staging, dev)" },
  { kind: "technology-standard", prefix: "TECH", domain: "delivery", description: "An approved technology standard" },
] as const;

/** Lookup helpers. */
export function getKindEntry(kind: string): EaKindEntry | undefined {
  return EA_KIND_REGISTRY.find((e) => e.kind === kind);
}

export function getKindsByDomain(domain: EaDomain): EaKindEntry[] {
  return EA_KIND_REGISTRY.filter((e) => e.domain === domain);
}

export function getKindPrefix(kind: string): string | undefined {
  return getKindEntry(kind)?.prefix;
}

export function getDomainForKind(kind: string): EaDomain | undefined {
  return getKindEntry(kind)?.domain;
}

// ─── ID Validation ──────────────────────────────────────────────────────────────

/**
 * Validates an EA artifact ID against the format: `{domain}/{PREFIX}-{slug}`
 * or the short form `{PREFIX}-{slug}`.
 */
export function isValidEaId(id: string, kind?: string): boolean {
  // Allow domain-qualified or short IDs
  const parts = id.includes("/") ? id.split("/") : [undefined, id];
  if (parts.length > 2) return false;

  const [domain, localId] = parts;

  // If domain provided, validate it
  if (domain && !EA_DOMAINS.includes(domain as EaDomain)) return false;

  // LocalId must be PREFIX-slug
  if (!localId || !localId.includes("-")) return false;

  // Extract prefix (everything before the first dash in slug portion)
  const dashIndex = localId.indexOf("-");
  const prefix = localId.substring(0, dashIndex);
  const slug = localId.substring(dashIndex + 1);

  if (!prefix || !slug) return false;

  // Slug must be kebab-case
  if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(slug)) return false;

  // If kind is provided, validate prefix matches
  if (kind) {
    const expected = getKindPrefix(kind);
    if (expected && expected !== prefix) return false;
  }

  return true;
}
